name: Boost Security Scanner
description: Scans a repository for vulnerabilities
author: https://boostsecurity.io
requirements:
  - bash
  - docker
  - mktemp
configuration:
  properties:
    additional_args:
      description: Additional CLI arguments to pass to boost cli
      type: string
    api_endpoint:
      description: Boost Security API endpoint override
      type: string
    api_token:
      description: Boost Security API token
      type: string
    docker_create_args:
      description: Additional arguments to pass to the docker create step
      type: string
    project_slug:
      description: Project unique name in the orgname/reponame form
      type: string
    scanner_image:
      description: Boost Security scanner image url override
      type: string
    scanner_version:
      description: Boost Security scanner version override
      type: string
  additionalProperties: false
  required:
    - api_token
